// Writes supabase/seed.sql from server/data/schedule.json.
// Usage: npm run supabase:seed  (then run the file in the Supabase SQL Editor)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { toRows, TABLES } from '../server/src/supabase.js';
import { validateSchedule } from '../server/src/schedule.js';

const source = fileURLToPath(new URL('../server/data/schedule.json', import.meta.url));
const target = fileURLToPath(new URL('../supabase/seed.sql', import.meta.url));
const schedule = validateSchedule(JSON.parse(readFileSync(source, 'utf8')));
const rows = toRows(schedule);

const literal = (value) => {
  if (value === null || value === undefined) return 'null';
  if (Array.isArray(value)) return `'{${value.map(Number).join(',')}}'`;
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
};

// Parents before children so foreign keys resolve.
const order = Object.keys(TABLES);
const lines = [
  '-- Generated by scripts/supabase-seed.mjs from server/data/schedule.json. Do not edit by hand.',
  '-- Run after schema.sql: SQL Editor -> New query -> paste -> Run. Re-running replaces all data.',
  'begin;',
  `truncate ${[...order].reverse().join(', ')} restart identity cascade;`,
];
for (const table of order) {
  const list = rows[table];
  if (!list.length) continue;
  const columns = Object.keys(list[0]);
  lines.push('', `insert into ${table} (${columns.join(', ')}) values`);
  lines.push(list.map(row => `  (${columns.map(column => literal(row[column])).join(', ')})`).join(',\n') + ';');
}
lines.push('', 'commit;', '');
writeFileSync(target, lines.join('\n'));
console.log(`Wrote ${target} (${order.map(table => `${table}: ${rows[table].length}`).join(', ')})`);
